spring.application.name : gateway-service-zuul
server.port : 8765

zuul:
  hosts:
    connect-timeout-millis: 200000
    socket-timeout-millis: 200000
  routes:
    -
      producer:
        -
          path : /customer/**
          serviceId : customer
        -
          path : /loan/**
          serviceId : loan

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://eureka:9091/eureka/
feign:
  hystrix:
    enabled : true
    


ribbon:
  ReadTimeout:4000